### ISSUE TITLE
Design of contributors listing page

### ISSUE THREAD

**Issue by o3LL** [Chaosthebot/Chaos#319]
Issue from this pr -> https://github.com/chaosbot/Chaos/pull/313
Let's continue discussion here 👍 

- [x]  Fix Object.values compatibility using .map() https://github.com/chaosbot/Chaos/pull/343
- [x]  CSS/Design overall https://github.com/chaosbot/Chaos/pull/376
- [x] Find a way to display list on homepage or elsewhere https://github.com/chaosbot/Chaos/pull/376

**Comment by Alexays** [comment]
May be do another card and then switchable between them with a sliding animation.
Ajax ?

**Comment by o3LL** [comment]
> May be do another card and then switchable between them with a sliding animation.

Why not, but the list is looooong

> Ajax ?

ajax is already working see -> https://github.com/chaosbot/Chaos/pull/313/commits

**Comment by o3LL** [comment]
Obects.value fixed here -> https://github.com/chaosbot/Chaos/pull/343

**Comment by mdcfe** [comment]
In #354, I've switched to a monospace font for the page to make it a little bit more readable, and added a prefix to show the positions of each voter.

I'm not convinced about making it look the same as the index page or using Bulma, though - it looks quite simple as it is.

**Comment by davidak** [comment]
>Find a way to display list on homepage or elsewhere

At least have a link on the homepage.

>>May be do another card and then switchable between them with a sliding animation.
>
>Why not, but the list is looooong

I like the idea.The list could be scrollable and only the first 10 visible...

It would be amazing to see the projects activity on the page!

**Comment by davidak** [comment]
Voters card will be added with https://github.com/chaosbot/Chaos/pull/376.

**Comment by MUCHZER** [comment]
All fixed in https://github.com/chaosbot/Chaos/pull/376 ! 🎆

**Comment by o3LL** [comment]
All fixed in https://github.com/chaosbot/Chaos/pull/376 ! 🎆

**Comment by mdcfe** [comment]
#376 doesn't fix the actual voters page, just adds a smaller list to the main page.

**Comment by o3LL** [comment]
> #376 doesn't fix the actual voters page, just adds a smaller list to the main page. 

Yep, but we dont need design on the voters.html list if there is one on the homepage ?

**Comment by mdcfe** [comment]
> there is one on the homepage
The homepage one only shows 20 entries, not the whole 300+ that there are.
